
# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net


name: Build RumbleReplayMod

on:
  workflow_dispatch:
    inputs:
      build_config:
        description: 'Build configuration (Debug/Release)'
        required: false
        default: 'Debug'
        type: string
  push:
    branches: [ "master" ]
    paths: 
     - 'RumbleReplayMod/**'
  pull_request:
    branches: [ "master" ]
    paths: 
     - 'RumbleReplayMod/**'

jobs:
  build:

    runs-on: windows-2025
    env:
      # Check if inputs.build_config exists (workflow_dispatch) or use Debug as fallback
      BUILD_CONFIG: ${{ github.event_name == 'workflow_dispatch' && inputs.build_config || 'Debug' }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
    
    - name: Download RUMBLE Dependencies  
      run: Invoke-WebRequest -Uri ${{secrets.REFERENCES}} -OutFile References.zip
    
    - name: Extract Dependencies
      run: Expand-Archive -Path References.zip -DestinationPath ./ -Force

    - name: Restore NuGet packages
      working-directory: RumbleReplayMod
      run: nuget restore

    - name: Build
      working-directory: RumbleReplayMod
      run: msbuild /p:Configuration=${{ env.BUILD_CONFIG }} /p:Platform=x64

    - name: Collect Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: RumbleReplay
        path: RumbleReplayMod/bin/x64/${{ env.BUILD_CONFIG }}/RumbleReplayMod.dll
