
name: Generate Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Build Release
        uses: ./.github/workflows/build.yml
        with:
          build_config: Release
      - name: Retrieve Build
        uses: dawidd6/action-download-artifact@v2
        with:
          name: RumbleReplay
          workflow: build.yml 
          workflow_conclusion: success 
          path: artifact.zip
      - name: Create directory
        run: mkdir Release
      - name: Extract mod from artifact.zip
        run: unzip artifact.zip -d Release/Mods
      - name: Fetch This Releases changelog 
        run: |
          CHANGELOG=$(awk '/^#/ {if (p) exit; p=1; next} p' CHANGELOG.md)
          echo "CHANGELOG=$CHANGELOG" >> $GITHUB_ENV
      - name: create misc files for Release
        run: |
          cp manifest.json Releases/manifest.json
          echo Source code can be found [here](https://github.com/blankochan/RumbleReplay) > Release/README.md
          cat README.md >> Release/README.md
          cp icon.png Release/icon.png
          cp CHANGELOG.md Release/CHANGELOG.md
      - name: Zip Release
        run: zip -r RumbleReplay.zip Release
      - name: Upload Release
        run: gh release create ${{ github.ref_name }} RumbleReplay.zip --title "Release ${{ github.ref_name }}" --notes "$CHANGELOG"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
