
name: Generate Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]'
jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets:
      REFERENCES: ${{secrets.REFERENCES}}
    with:
      build_config: 'Release'
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create directory
        run: mkdir Release
      - name: Retrieve Build
        uses: dawidd6/action-download-artifact@v6
        with:
          name: RumbleReplay
          workflow: build.yml 
          workflow_conclusion: success 
          path: Release/Mods
      - name: Fetch This Releases changelog 
        run: awk '/^#/ {if (p) exit; p=1; next} p' CHANGELOG.md > releaseChanges.txt
      - name: create misc files for Release
        run: |
          cp manifest.json Release/manifest.json
          echo "Source code can be found [here](https://github.com/blankochan/RumbleReplay)" > Release/README.md
          cat README.md >> Release/README.md
          cp icon.png Release/icon.png
          cp CHANGELOG.md Release/CHANGELOG.md
      - name: Zip Release
        run: cd folder && zip -r ../RumbleReplay.zip ./*

      - name: Upload Release
        run: gh release create ${{ github.ref_name }} RumbleReplay.zip --title "Release ${{ github.ref_name }}" --notes-file releaseChanges.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
